services:
  bombsquad:
    build:
      context: .
      args:
        BOMBSQUAD_VERSION: "1.7.43"
    image: bombsquad-dockerized
    restart: unless-stopped
    ports:
      - "43210:43210/udp"
    volumes:
      - bombsquad-data:/data
    environment:
      PARTY_NAME: "My Server"
      SESSION_TYPE: "ffa"
      FFA_SERIES_LENGTH: "24"
      # HTTP_PROXY: "http://host.docker.internal:9010"
      # HTTPS_PROXY: "http://host.docker.internal:9010"

volumes:
  bombsquad-data:
